baseURL = 'https://nbonato.github.io/'
languageCode = 'en-us'
title = 'Anna Vicco'
theme = "exampleTheme"


[params]
  [[params.social]]
    name = "Linkedin"
    pre = "linkedin"
    url = "https://www.linkedin.com/in/anna-vicco"
  [[params.social]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/AnnaV"
  [[params.social]]
    name = "Orcid"
    pre = "orcid"
    url = "https://orcid.org/0000-0002-6555-3090"

[menu]
  [[menu.main]]
    name = "Publications"
    pre = "fa-solid fa-book-bookmark"# pre is used to load icons
    url = "/publications/"
    weight = 2
  [[menu.main]]
    name = "CV"
    pre = "fa-solid fa-briefcase"
    url = "/cv/"
    weight = 3
  [[menu.main]]
    name = "Teaching"
    pre = "fa-solid fa-chalkboard-user"
    url = "/teaching/"
    weight = 3
